name: zepar
description: A wrapper for http and html packages
version: 1.1.1

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.10.1'

dependencies:
  html: ^0.15.4
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter