name: zepar
description: A wrapper for http and html packages
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '>=3.3.9'

dependencies:
  html: ^0.15.1
  http: ^0.13.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1